insert into name (value) values 
	('Sabina'), 
	('Honoria'), 
	('Tránsito'), 
	('Higinio'), 
	('Ufano'), 
	('Hilario'), 
	('Jacinta'), 
	('Cándido'), 
	('Teodosia'), 
	('Cástulo'), 
	('Gervasia'), 
	('Epifanio'), 
	('Gaudelia'), 
	('Eufemio'), 
	('Eustaquio'), 
	('Brígida'), 
	('Melitón'), 
	('Leonila'), 
	('Nicanor'), 
	('Martina'), 
	('Régulo'), 
	('Teodora'), 
	('Teódulo'), 
	('Tiburcio'), 
	('Celso (toda una vida pensando que se llamaba Sexo, tremendo)') on conflict do nothing;