services:
  postgresql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=my-db
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
    ports:
      - 5432
    labels:
      - "org.springframework.boot-service-connection=postgres"